// https://sites.highlands.edu/tutorial-center/tutor-resources/online-tutor-training/module-3/fifty-ways-to-praise-your-students/
export const correctComments = [
    `Good!`,
    `You’ve got it right!`,
    `That’s right!`,
    `Super!`,
    `That’s good!`,
    `You’re really working hard today!`,
    `You are very good at that!`,
    `That’s coming along nicely!`,
    `Good work!`,
    `That’s much better!`,
    `Exactly right!`,
    `You just about have it!`,
    `That’s it!`,
    `You are doing a good job!`,
    `That’s quite an improvement!`,
    `Great!`,
    `I knew you could do it!`,
    `Congratulations!`,
    `Not bad!`,
    `Now you have it!`,
    `Good for you!`,
    `I couldn’t have done it better!`,
    `That’s the way to do it!`,
    `You’re on the right track now!`,
    `Nice going!`,
    `Keep up the good work!`,
    `Sensational!`,
    `You’ve got your brain in gear!`,
    `That was first class work!`,
    `Excellent!`,
    `Perfect!`,
    `That’s better than ever!`,
    `Much better!`,
    `Wonderful!`,
    `You must have been practicing!`,
    `You did that very well!`,
    `Nice going!`,
    `Outstanding!`,
    `Fantastic!`,
    `That’s the way to handle it!`,
    `That’s great!`,
    `Right on!`,
    `Superb!`,
    `You did a lot of work today!`,
    `That’s it!`,
    `Thank you!`,
    `Good thinking!`,
    `You out did yourself today!`,
    `Good attempt!`,
    `You figured that out fast!`,
];

export const incorrectComments = [
    `That's incorrect.`,
    `That’s not right.`,
    `Try again.`,
    `Don’t give up.`,
    `Keep trying.`,
    `You can do this.`,
    `That's okay, try again.`,
    `Give it another try.`,
    `I believe you can do this.`,
    `Hang in there.`,
    `You've got this.`,
    `Stay focused.`,
    `I know you've got this.`,
];